const SEED_ENTRIES = [
  {
    id: "e-camping-muslim",
    title: "Camping is Muslim",
    date: "May 6, 2026",
    mood: "grounded",
    weather: "—",
    tint: 4,
    body: [""],
    photos: [],
  },
  {
    id: "e-quitting",
    title: "I'm quitting or something.",
    date: "Apr 2, 2026",
    mood: "restless",
    weather: "—",
    tint: 3,
    body: [""],
    photos: [],
  },
  {
    id: "e-family",
    title: "Family",
    date: "Mar 28, 2026",
    mood: "heavy",
    weather: "—",
    tint: 7,
    body: [""],
    photos: [],
  },
  {
    id: "e-opinion",
    title: "Your opinion isn't valid",
    date: "Mar 28, 2026",
    mood: "sharp",
    weather: "—",
    tint: 6,
    body: [""],
    photos: [],
  },
  {
    id: "e-emotional-dump",
    title: "emotional dump",
    date: "Mar 21, 2026",
    mood: "raw",
    weather: "—",
    tint: 5,
    body: [""],
    photos: [],
  },
  {
    id: "e-night-voice",
    title: "Night voice dump",
    date: "Mar 9, 2026",
    mood: "late",
    weather: "—",
    tint: 8,
    body: [""],
    photos: [],
  },
  {
    id: "e-overland",
    title: "Overland build?",
    date: "Feb 14, 2026",
    mood: "curious",
    weather: "—",
    tint: 2,
    body: [""],
    photos: [],
  },
  {
    id: "e-guidance",
    title: "i could use some guidance and support.",
    date: "Feb 2, 2026",
    mood: "searching",
    weather: "—",
    tint: 1,
    body: [""],
    photos: [],
  },
  {
    id: "e-rage",
    title: "I feel rage.",
    date: "Jan 16, 2026",
    mood: "charged",
    weather: "—",
    tint: 6,
    body: [""],
    photos: [],
  },
  {
    id: "e-maniac",
    title: "You should be a maniac.",
    date: "Jan 16, 2026",
    mood: "fired up",
    weather: "—",
    tint: 3,
    body: [""],
    photos: [],
  },
  {
    id: "e-kids-theory",
    title: "my theory on kids, for our generation.",
    date: "Dec 6, 2025",
    mood: "thinking",
    weather: "—",
    tint: 4,
    body: [""],
    photos: [],
  },
  {
    id: "e-compete",
    title: "I want to compete man.",
    date: "Nov 27, 2025",
    mood: "hungry",
    weather: "—",
    tint: 2,
    body: [""],
    photos: [],
  },
  {
    id: "e-umrah",
    title: "umrah, Alhamdilah.",
    date: "Nov 27, 2025",
    mood: "grateful",
    weather: "—",
    tint: 1,
    body: [""],
    photos: [],
  },
  {
    id: "e-journey-begins",
    title: "the journey begins.",
    date: "Nov 20, 2025",
    mood: "open",
    weather: "—",
    tint: 7,
    body: [""],
    photos: [],
  },
];

export default SEED_ENTRIES;
