const SEED_ENTRIES = [
  {
    id: "e-nov-light",
    title: "The light at the edge of November",
    date: "Nov 11, 2025",
    mood: "tender",
    weather: "47° • clear",
    tint: 2,
    body: [
      "Walked the long way home along the canal. The sun was already low at four — that pale gold that only happens in November, when the year is folding itself up to sleep.",
      "I kept thinking about how nobody talks about light like a feeling. But it is one. Today's was the kind that makes you stop and wonder what you've been doing with the year.",
      "Picked up two persimmons on the way back. They're sitting on the windowsill now, looking like small suns.",
    ],
  },
  {
    id: "e-mom-called",
    title: "Mom called for no reason",
    date: "Nov 9, 2025",
    mood: "warm",
    weather: "52° • drizzle",
    tint: 6,
    body: [
      "Just to say hi. We talked for forty minutes about absolutely nothing — her neighbor's lemon tree, what she's reading, whether I should buy the boots.",
      "I keep noticing that her voice has gotten softer. Or maybe I've gotten better at listening. Hard to tell which.",
      "She told me a story about her mother I'd never heard. A whole secret summer in 1962.",
    ],
  },
  {
    id: "e-bread",
    title: "I tried bread again",
    date: "Nov 6, 2025",
    mood: "stubborn",
    weather: "44° • windy",
    tint: 7,
    body: [
      "Fourth attempt. Still flat. The kitchen smells like yeast and quiet defeat.",
      "But the crumb was almost right this time. I could see it — a little bit of the airy, glossy thing that real bread does. Just for a second, before it deflated.",
      "Going to give it one more try on Sunday. New flour. New patience.",
    ],
  },
  {
    id: "e-cat-sun",
    title: "The cat found the sunbeam",
    date: "Nov 4, 2025",
    mood: "small joy",
    weather: "55° • bright",
    tint: 3,
    body: [
      "She moved across the floor for an hour, following it. The most committed creature I have ever known.",
      "I sat on the rug and watched her until my coffee got cold. Worth it.",
    ],
  },
  {
    id: "e-3am",
    title: "Finished the book at 3am",
    date: "Nov 2, 2025",
    mood: "wrung out",
    weather: "40° • clear",
    tint: 5,
    body: [
      "Couldn't put it down. The last hundred pages went by like a held breath.",
      "I closed it and just sat there in the dark with the lamp still on, trying to decide whether to be grateful or annoyed at the author for what she did.",
      "Both, probably. That's how you know it was good.",
    ],
  },
  {
    id: "e-first-snow",
    title: "First snow, before anyone else was up",
    date: "Oct 30, 2025",
    mood: "still",
    weather: "31° • snow",
    tint: 5,
    body: [
      "I made coffee in the dark and stood at the kitchen window. The street looked like a held note.",
      "No footprints yet. No tire tracks. Just the streetlight, and everything underneath it slightly blurred and new.",
      "Five minutes of feeling like the only person in the world. Then the radiator clanked and the spell broke.",
    ],
  },
  {
    id: "e-david",
    title: "Coffee with David, who is moving",
    date: "Oct 28, 2025",
    mood: "bittersweet",
    weather: "58° • overcast",
    tint: 4,
    body: [
      "He's leaving in February. Portland. We've been saying we'd get coffee for six months and now it's the goodbye coffee.",
      "He looks happier than I've seen him in years. I'm trying very hard to be glad about that and not selfish about it. Mostly succeeding.",
    ],
  },
  {
    id: "e-sweater",
    title: "Threw out the green sweater",
    date: "Oct 25, 2025",
    mood: "lighter",
    weather: "50° • clear",
    tint: 4,
    body: [
      "Nine years. Two apartments. One breakup. The elbows finally went and I sat on the floor of my closet for a while before I could put it in the bag.",
      "Funny how a piece of wool can hold so much.",
    ],
  },
  {
    id: "e-six-years",
    title: "Six years",
    date: "Oct 22, 2025",
    mood: "grateful",
    weather: "62° • golden",
    tint: 1,
    body: [
      "Six years today. I almost didn't notice — that's the gift, I guess.",
      "Made myself a quiet dinner. Lit a candle. Wrote a thank-you list. Slept well.",
    ],
  },
  {
    id: "e-piano",
    title: "Practice felt good today",
    date: "Oct 19, 2025",
    mood: "in flow",
    weather: "48° • sunny",
    tint: 8,
    body: [
      "The Bach finally clicked. Not the whole thing — just the second page, the part with the cross-hand jump that I've been butchering for a month.",
      "Played it through cleanly four times in a row. Then I got cocky and ruined it. Still — I had it. I know I had it.",
    ],
  },
  {
    id: "e-stranger",
    title: "A stranger told me my coat was lovely",
    date: "Oct 16, 2025",
    mood: "buoyant",
    weather: "53° • crisp",
    tint: 6,
    body: [
      "On the platform at 14th Street. She didn't even break stride, just smiled and said it as she walked past.",
      "I thought about it the whole train ride. Still thinking about it now.",
    ],
  },
  {
    id: "e-soup",
    title: "Made the soup from memory",
    date: "Oct 13, 2025",
    mood: "rooted",
    weather: "46° • rain",
    tint: 7,
    body: [
      "No recipe. Just what my hands remembered from watching my grandmother do it a hundred times when I was small.",
      "Onions slow until they go translucent. Garlic late so it doesn't burn. A pinch more salt than feels right. The bay leaf you forget to fish out.",
      "Tasted exactly like her kitchen. I cried a little, in a good way.",
    ],
  },
];

export default SEED_ENTRIES;
